### ISSUE TITLE
[BUG] Blank screen on Windows

### ISSUE THREAD

**Issue by max20091** [AkiChase/scrcpy-mask#17]
**Describe the bug**
Blank screen after connected.
![image](https://github.com/AkiChase/scrcpy-mask/assets/12845078/6a9f05fc-23f5-4fa2-9fec-00e2cd17f5eb)

**To Reproduce**
1. Connect device through wired ADB
2. Start scrcpy server
3. Blank screen

**Expected behavior**
Should show the screen,
Scrcpy from Genymotion works normally.
**Environment  (please complete the following information):**
 - OS: Windows 11
 - Version 23H2
 - Phone: Samsung Galaxy S22 Android 14

**Comment by AkiChase** [comment]
You missed the README.

Due to the delay and blurred image quality of the mirror screen. This project found another way, directly abandoned the mirror screen, and instead used a transparent mask to display the screen content behind the window, which fundamentally put an end to the delay in casting the screen.

Please read the basic usage.
