### ISSUE TITLE
[BUG] 获取不到手机画面，但是可以操作手机

### ISSUE THREAD

**Issue by HumanMus1c** [AkiChase/scrcpy-mask#51]
**Describe the bug**

![VID_20240524_133300_小萌GIF_20240524_133729](https://github.com/AkiChase/scrcpy-mask/assets/46023154/7b356499-2a2a-40dc-9bee-23f7ade6e897)

**To Reproduce**
1. 启动
2. 连接
3. 连接成功
4. 获取不到手机画面，但是可以操作手机

**Expected behavior**
既可以获取到手机画面，也可以操作手机

**Screenshots**
![VID_20240524_133300_小萌GIF_20240524_133729](https://github.com/AkiChase/scrcpy-mask/assets/46023154/7b356499-2a2a-40dc-9bee-23f7ade6e897)

**Environment  (please complete the following information):**
Windows:

处理器	AMD Ryzen 5 5600X 6-Core Processor                3.70 GHz
机带 RAM	16.0 GB
设备 ID	3DBB1718-50EF-4F15-A79B-4B9A0607D298
产品 ID	00330-80000-00000-AA784
系统类型	64 位操作系统, 基于 x64 的处理器
笔和触控	没有可用于此显示器的笔或触控输入

手机:
![Screenshot_20240524_134713](https://github.com/AkiChase/scrcpy-mask/assets/46023154/524d8ad4-836d-4e7a-8150-66229f350998)

**Additional context**

**Comment by AkiChase** [comment]
请认真阅读README



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月24日(周五) 中午1:54
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [AkiChase/scrcpy-mask] [BUG] 获取不到手机画面，但是可以操作手机 (Issue #51)




 
Describe the bug
 
VID_20240524_133300_.GIF_20240524_133729.gif (view on web)
 
To Reproduce
 Steps to reproduce the behavior:
  
启动
 
连接
 
连接成功
 
获取不到手机画面，但是可以操作手机
  
Expected behavior
 既可以获取到手机画面，也可以操作手机
 
Screenshots
 VID_20240524_133300_.GIF_20240524_133729.gif (view on web)
 
Environment  (please complete the following information):
 Windows:
 
处理器	AMD Ryzen 5 5600X 6-Core Processor                3.70 GHz
 机带 RAM	16.0 GB
 设备 ID	3DBB1718-50EF-4F15-A79B-4B9A0607D298
 产品 ID	00330-80000-00000-AA784
 系统类型	64 位操作系统, 基于 x64 的处理器
 笔和触控	没有可用于此显示器的笔或触控输入
 
手机:
 
Additional context
 Add any other context about the problem here.

**Comment by BuShouFan** [comment]
哥们
![image](https://github.com/AkiChase/scrcpy-mask/assets/126171728/4ce66928-511e-446e-8fd9-dfb500cb93d5)
